spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    data: classpath:/db/populate_db.sql
    url: jdbc:h2:mem:testdb
    username: wichtelnisse
  h2:
    console:
      enabled: true
      path: /h2-console